// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj2NSKXSfaLXr0Gl1GlL-3QOStX027bC4',
    appId: '1:788248811357:web:b1b0d4eb6ed52710e43ab4',
    messagingSenderId: '788248811357',
    projectId: 'sima-orbit',
    authDomain: 'sima-orbit.firebaseapp.com',
    storageBucket: 'sima-orbit.appspot.com',
    measurementId: 'G-9SEYC2QWTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxhp9umhhNVIeKQ1nAZNaI-60NhnEHT_Y',
    appId: '1:788248811357:android:b67d4db597b47864e43ab4',
    messagingSenderId: '788248811357',
    projectId: 'sima-orbit',
    storageBucket: 'sima-orbit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDErb7VCRf7FfHtrwTOpywbFckqkGkGuj8',
    appId: '1:788248811357:ios:400dfb65891992fee43ab4',
    messagingSenderId: '788248811357',
    projectId: 'sima-orbit',
    storageBucket: 'sima-orbit.appspot.com',
    iosClientId: '788248811357-2mfemfvljuvrl6o45gm3j7qi7nfo6sh5.apps.googleusercontent.com',
    iosBundleId: 'com.gariskode.simaOrbitMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDErb7VCRf7FfHtrwTOpywbFckqkGkGuj8',
    appId: '1:788248811357:ios:400dfb65891992fee43ab4',
    messagingSenderId: '788248811357',
    projectId: 'sima-orbit',
    storageBucket: 'sima-orbit.appspot.com',
    iosClientId: '788248811357-2mfemfvljuvrl6o45gm3j7qi7nfo6sh5.apps.googleusercontent.com',
    iosBundleId: 'com.gariskode.simaOrbitMobile',
  );
}
